import './style.css';
type CreatedAgent = { id: string }; type ChatMessage = { role: 'user' | 'agent'; text: string };
const canvas = document.querySelector<HTMLElement>('#canvas')!, createButton = document.querySelector<HTMLButtonElement>('#create-agent')!, agentCount = document.querySelector<HTMLElement>('#agent-count')!, feedback = document.querySelector<HTMLElement>('#feedback')!, chatPanel = document.querySelector<HTMLElement>('#chat-panel')!, chatTitle = document.querySelector<HTMLElement>('#chat-title')!, messagesElement = document.querySelector<HTMLElement>('#messages')!, messageForm = document.querySelector<HTMLFormElement>('#message-form')!, messageInput = document.querySelector<HTMLInputElement>('#message-input')!, closeChat = document.querySelector<HTMLButtonElement>('#close-chat')!;
const conversations = new Map<string, ChatMessage[]>(); let selectedAgentId: string | null = null; let totalAgents = 0; let spawnIndex = 0;
function updateCount() { agentCount.textContent = `${totalAgents} ${totalAgents === 1 ? 'agente' : 'agentes'}`; }
function renderConversation() { messagesElement.replaceChildren(); if (!selectedAgentId) return; const messages = conversations.get(selectedAgentId) ?? []; if (!messages.length) messagesElement.innerHTML = '<p class="empty-chat">Envía un mensaje para iniciar la conversación.</p>'; for (const message of messages) { const item = document.createElement('p'); item.className = `message ${message.role}`; item.textContent = message.text; messagesElement.append(item); } messagesElement.scrollTop = messagesElement.scrollHeight; }
function openConversation(agentId: string) { selectedAgentId = agentId; if (!conversations.has(agentId)) conversations.set(agentId, []); chatTitle.textContent = agentId; chatPanel.classList.add('is-open'); chatPanel.setAttribute('aria-hidden', 'false'); renderConversation(); messageInput.focus(); }
function closeConversation() { selectedAgentId = null; chatPanel.classList.remove('is-open'); chatPanel.setAttribute('aria-hidden', 'true'); }
function createAgentNode(agent: CreatedAgent) {
  const node = document.createElement('button'); node.className = 'agent-node'; node.type = 'button'; node.dataset.agentId = agent.id; node.setAttribute('aria-label', `Agente ${agent.id}. Haz clic para conversar o arrástralo para moverlo.`); node.innerHTML = '<span class="agent-core"></span><span class="agent-tooltip"></span>'; node.querySelector<HTMLElement>('.agent-tooltip')!.textContent = agent.id;
  const rect = canvas.getBoundingClientRect(), offset = (spawnIndex++ % 6) * 28; node.style.left = `${Math.min(rect.width - 62, Math.max(26, rect.width / 2 - 26 + offset))}px`; node.style.top = `${Math.min(rect.height - 62, Math.max(42, rect.height / 2 - 26 + offset))}px`;
  let pointerOffsetX = 0, pointerOffsetY = 0, moved = false;
  node.addEventListener('pointerdown', (event) => { event.preventDefault(); moved = false; const nodeRect = node.getBoundingClientRect(); pointerOffsetX = event.clientX - nodeRect.left; pointerOffsetY = event.clientY - nodeRect.top; node.classList.add('is-dragging'); node.setPointerCapture(event.pointerId); });
  node.addEventListener('pointermove', (event) => { if (!node.hasPointerCapture(event.pointerId)) return; const canvasRect = canvas.getBoundingClientRect(), left = Math.max(0, Math.min(canvasRect.width - node.offsetWidth, event.clientX - canvasRect.left - pointerOffsetX)), top = Math.max(0, Math.min(canvasRect.height - node.offsetHeight, event.clientY - canvasRect.top - pointerOffsetY)); if (Math.abs(parseFloat(node.style.left) - left) > 2 || Math.abs(parseFloat(node.style.top) - top) > 2) moved = true; node.style.left = `${left}px`; node.style.top = `${top}px`; });
  const endDrag = (event: PointerEvent) => { if (node.hasPointerCapture(event.pointerId)) node.releasePointerCapture(event.pointerId); node.classList.remove('is-dragging'); if (!moved) openConversation(agent.id); }; node.addEventListener('pointerup', endDrag); node.addEventListener('pointercancel', endDrag); canvas.append(node);
}
async function requestAgent() { createButton.disabled = true; feedback.textContent = 'Validando creación de chat…'; try { const response = await fetch('/api/chats', { method: 'POST' }); if (!response.ok) throw new Error('El servidor rechazó la creación.'); const result = await response.json() as { allowed: boolean; agent?: CreatedAgent }; if (!result.allowed || !result.agent) throw new Error('No se pudo crear el agente.'); createAgentNode(result.agent); totalAgents += 1; updateCount(); feedback.textContent = `Agente ${result.agent.id} creado.`; } catch (error) { feedback.textContent = error instanceof Error ? error.message : 'No fue posible conectar con el backend.'; } finally { createButton.disabled = false; } }
async function sendMessage(event: SubmitEvent) { event.preventDefault(); const agentId = selectedAgentId, text = messageInput.value.trim(); if (!agentId || !text) return; const conversation = conversations.get(agentId)!; conversation.push({ role: 'user', text }); messageInput.value = ''; renderConversation(); try { const response = await fetch(`/api/message/${encodeURIComponent(agentId)}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ message: text }) }); if (!response.ok) throw new Error('No se recibió respuesta del agente.'); const result = await response.json() as { reply: string }; conversation.push({ role: 'agent', text: result.reply }); } catch (error) { conversation.push({ role: 'agent', text: error instanceof Error ? error.message : 'Error al conectar con el agente.' }); } renderConversation(); }
createButton.addEventListener('click', requestAgent); messageForm.addEventListener('submit', sendMessage); closeChat.addEventListener('click', closeConversation);
